### ISSUE TITLE
How to skip cli authentication if run locally?

### ISSUE THREAD

**Issue by gentlee** [microsoft/code-push-server#13]
There is a `DEBUG_DISABLE_AUTH` env but looks like it doesn't make it work.

**Comment by gentlee** [comment]
There is a line in ENVIRONMENT.md about it:

```
DEBUG_DISABLE_AUTH: Disable the OAuth autentication route, allowing you to make requests as anybody without authorizing. Do not set this without going through the proper channels (see section Disabling Auth)
```

But there is no `Disabling Auth` section in the repo.

**Comment by lucen-ms** [comment]
We have updated readme to clarify how skipping authentication works.

**Comment by gentlee** [comment]
@lucen-ms so when running locally, is it possible to skip OAuth step and create `existing user` under which use the app, together with cli?

**Comment by lucen-ms** [comment]
It's not possible - you need to add user via OAuth step first.
