### ISSUE TITLE
Codepush signing of release

### ISSUE THREAD

**Issue by danielpetersson** [microsoft/code-push-server#23]
We are currently using appcenter codepush CLI to release update. We are using --private-key-path to sign the update. Releasing with the [react-native-code-push](https://github.com/microsoft/react-native-code-push) CLI doesn't have support for --private-key-path which causes the app (which verifies the downloaded update) to output:

10-16 10:19:51.588   966   966 D ReactNative: [CodePush] Loading JS bundle from "assets://index.android.bundle"
10-16 10:19:53.599   966  1085 D ReactNative: [CodePush] Applying full update.
10-16 10:19:53.601   966  1085 E ReactNative: [CodePush] Exception
10-16 10:19:53.601   966  1085 E ReactNative: com.microsoft.codepush.react.CodePushInvalidUpdateException: Error! Public key was provided but there is no JWT signature within app bundle to verify. Possible reasons, why that might happen: 
10-16 10:19:53.601   966  1085 E ReactNative: 1. You've been released CodePush bundle update using version of CodePush CLI that is not support code signing.
10-16 10:19:53.601   966  1085 E ReactNative: 2. You've been released CodePush bundle update without providing --privateKeyPath option.
10-16 10:19:53.601   966  1085 E ReactNative:   at com.microsoft.codepush.react.CodePushUpdateManager.downloadPackage(CodePushUpdateManager.java:278)
10-16 10:19:53.601   966  1085 E ReactNative:   at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:298)
10-16 10:19:53.601   966  1085 E ReactNative:   at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:292)
Should we sign the update as a pre-step to "code-push-standalone release-react" or can we, and is it recommended, to somehow disable the need of validating signing in our app?

**Comment by lucen-ms** [comment]
I'm sorry the current version does not support code signing but we will add it soon to have a feature parity with the current `appcenter-cli` version.

**Comment by lucen-ms** [comment]
Codepush signing has been implemented

**Comment by dorit-lt** [comment]
I am still seeing this issue even when I codesign using --privateKeyPath.

**Comment by saransh-malik** [comment]
Yup still not working, I see when releasing it says "Generated a release signature and wrote it " but even then the download fails. The private key pair we use is the same as before and so I am sure I am using the right public key in the app.

**Comment by dorit-lt** [comment]
I have this issue only when i try to specify an output directory. Something with code signing seems to get messed up when that is defined.

**Comment by saransh-malik** [comment]
@lucen-ms That's the way to replicate it, the signing doesn't work if you specify an output directory. Can we please re-open this?

**Comment by lucen-ms** [comment]
@saransh-malik we are not going to fix this issue but feel free to issue a PR with fix.

**Comment by saransh-malik** [comment]
@lucen-ms Okay sure thanks, will debug more I think I found the code in the original cli will try to fix and create a PR.
