### ISSUE TITLE
Need frontend repository of AppCenter

### ISSUE THREAD

**Issue by shail4998** [microsoft/code-push-server#27]
Hi, Can you share the frontend repository of AppCenter? So that we can manage code-push deployments efficiently.
Since it already has GUI features supporting rollbacks, managing codepush percentage and all.
Thanks.

**Comment by lucen-ms** [comment]
This CodePush version does not have GUI version.

**Comment by rahman2835** [comment]
@lucen-ms what if I wanted to implemented front end changes using react js?

**Comment by lucen-ms** [comment]
@rahman2835 sure - go for it in your fork.
