### ISSUE TITLE
The session or access key being used is invalid, please run "code-push-standalone login" again. If you are on an older version of the CLI, you may need to run "code-push-standalone logout" first to clear the session cache.

### ISSUE THREAD

**Issue by puresprout** [microsoft/code-push-server#31]
Hello.

I have set up the code-push-server environment locally with the following file.

.env
```
EMULATED=true
DEBUG_DISABLE_AUTH=true
```

The server was run normally with `npm run start:env`

But in the cli

`code-push-standalone register http://localhost:3000`

or

`code-push-standalone login http://localhost:3000`

When you run the above, you will get an error in your browser like this:

`The session or access key being used is invalid, please run "code-push-standalone login" again. If you are on an older version of the CLI, you may need to run "code-push-standalone logout" first to clear the session cache.`

Of course, even if I tried the logout command as below, it didn't work.

`code-push-standalone login`

If you set the .env file of code-push-server as follows

```
DEBUG_DISABLE_AUTH=false
```

The following error appears in your browser:

`Please select an authentication provider for your CodePush account:`

However, there are no authentication providers to choose from.

How do I do this?

If it is absolutely necessary to set up the github authentication provider, please let me know how.

**Comment by DavidKostDev** [comment]
Hey,

I faced it too and solved tho now I'm facing a new error XD,
you have to setup OAuth with either Github or Microsoft and add an additional env variables to your API .env:
EMULATED='true'
LOGGING='true'
SERVER_URL='http://localhost:3000'
**GITHUB_CLIENT_ID='SECRET'
GITHUB_CLIENT_SECRET='SECRET'**

Hopefully it helps and get's you one step closer.

There's a similar issue you can look for info there maybe you will see something useful:
[https://github.com/microsoft/code-push-server/issues/10](url)

**Comment by DavidKostDev** [comment]
I followed this tutorial and made sure I follow the README.MD
[https://www.youtube.com/watch?v=BbJt6HpZnNU](url)


### GitHub
1. Go to https://github.com/settings/developers
1. Click on `New OAuth App`
1. `Homepage URL` parameter will be the same as URL of your CodePush application on Azure - `https://codepush-<project-suffix>.azurewebsites.net` (for local development it will be either http://localhost:3000 or https://localhost:8443)
**1. `Authorization callback URL` will be `https://codepush-<project-suffix>.azurewebsites.net/auth/callback/github` (for local development it will be either http://localhost:3000/auth/callback/github or https://localhost:8443/auth/callback/github)**

let me know if it works.


Pay attention to change Authorization callback URL "http://localhost:3000/" in github app to be:
http://localhost:3000/auth/callback/github

**Comment by puresprout** [comment]
@DavidKostDev 

Thanks.
But before you say anything, I also read the document and set the callback url to http://localhost:3000/auth/callback/github, but I still get the error below.

```
Denied by Groxy
```

Is this a problem with the company's network security or firewall?

**Comment by puresprout** [comment]
Thanks, @DavidKostDev 

I confirmed that it works normally because the company took measures to bypass network security.
It seems that I have to start azurite first before starting the code-push server.

Thank you for your help.

**Comment by DavidKostDev** [comment]
@puresprout  Did you manage to make it work ?

**Comment by puresprout** [comment]
@DavidKostDev Yes. It works. Thanks for you
