### ISSUE TITLE
Invalid Session or Access Key Error on /apps Page

### ISSUE THREAD

**Issue by RyuJeongSang** [microsoft/code-push-server#32]
Hello,

I am currently using code-push-server, and when I open the `https://{project name}.azurewebsites.net/apps` page in my browser, I see the following error message:

```
The session or access key being used is invalid, please run "code-push-standalone login" again. If you are on an older version of the CLI, you may need to run "code-push-standalone logout" first to clear the session cache.
```
This error makes it challenging to check the deployment history of CodePush on the /apps console, which was accessible in the previous version of AppCenter CodePush.

The functionality to view the CodePush deployment history and uploaded content on the /apps page in the previous AppCenter CodePush was very useful.

To resolve this issue, I have taken the following actions:

1. Executed the `code-push-standalone login` command, but the same error persists.
2. `code-push-standalone logout`, and then attempted to log in again.

I would appreciate any solutions or additional information you could provide. I hope this functionality can be restored soon.

Thank you.

**Comment by rahman2835** [comment]
@RyuJeongSang I'm also getting the same issue. What is the work around for this issue?
