### ISSUE TITLE
Problem with code-push-standalone debug ios command

### ISSUE THREAD

**Issue by nscille** [microsoft/code-push-server#33]
I've been having issues with installing updates on iOS and tried using the debug command `code-push-standalone debug ios` to check for issues, but it's always returning the following error: `[Error]  output.json.devices.map is not a function`. The command works fine with Android but I haven't been able to get it to work with iOS. I have a local server running on http://localhost:3000, as well as azurite.

**Comment by nscille** [comment]
I managed to get the debug command working by changing the `getSimulatorID` method in `cli/script/commands/debug.ts` to this:
```
private getSimulatorID(): string {
    const output: any = simctl.list({ devices: true, silent: true });
    const simulators: string[] = Object.values(output.json.devices)
      .flat()
      .filter((device: any) => device.state === "Booted")
      .map((device: any) => device.udid);

    return simulators[0];
  }
```
You'll have to run `npm run build` after making the change

**Comment by romanfanatics** [comment]
It worked for me, thank you !
