### ISSUE TITLE
InternalOAuthError: Failed to fetch user profile (OAuth error)

### ISSUE THREAD

**Issue by DavidKostDev** [microsoft/code-push-server#35]
I'm getting a redirect to the OAuth of Github:
![Image](https://github.com/user-attachments/assets/1e82d806-573c-4eb3-b70a-8c3cf0e4735b)
I authorize the app and I get redirected to the auth/callback/github link:
http://localhost:3000/auth/callback/github?code=[SOME_CODE]&state=[SOME_CODE]
After the redirect I get an error that comes from the code-push-server - **api**,
**The Error I get:**
![Image](https://github.com/user-attachments/assets/901094fe-d1ef-4b0d-89c9-2eacc8a7ab13)
 (I'm still looking into it, if anyone has any advice would like to hear).

@puresprout

**Comment by puresprout** [comment]
It seems like redirecting happens many.
Please confirm company network firewall or policy.

Retry All step from start.

I'm not sure why

**Comment by msutormin** [comment]
I took me a while to figure it out, but it's important to create an OAuth App and not a GitHub App

![Image](https://github.com/user-attachments/assets/08d0e29d-7466-45f8-af46-61ff4c68a3a2)
