### ISSUE TITLE
Usage of the /common endpoint not supported for applications created after 10/15/2018

### ISSUE THREAD

**Issue by kmcrawford** [microsoft/code-push-server#39]
![Image](https://github.com/user-attachments/assets/460a6419-2dcd-4761-9c6b-edfca96fc12e)

I believe this error is due to this line of code.  The `tenantId` should be used vs `common`.

https://github.com/microsoft/code-push-server/blob/main/api/script/routes/passport-authentication.ts#L491

**Comment by lucen-ms** [comment]
We have added support for single tenant.
