### ISSUE TITLE
Regarding the release of the version including Cordova

### ISSUE THREAD

**Issue by ShojiSato** [microsoft/code-push-server#4]
Previously, it was possible to use CodePush with apps developed using Cordova on Microsoft AppCenter.
I believe there should also be code for CodePushServer and CLI.
Could you publish it as a separate branch?

**Comment by lucen-ms** [comment]
We do not support Cordova anymore, but you can fork the code and add the support.

**Comment by talavidan4** [comment]
HI @ShojiSato , 
Did you manage to add cordova support?
