### ISSUE TITLE
Switching to Azure Storage from local not working

### ISSUE THREAD

**Issue by jerinjohnk** [microsoft/code-push-server#40]
<strike> While switching to azure storage.
1) The github Authorization url callback 
`.auth/login/github/callback` 
worked instead of 
`auth/callback/github` 
as specified in the [Readme](https://github.com/microsoft/code-push-server/blob/main/api/README.md#github). 
Is this correct?

2) Once I allow github access while registering using 
`code-push-standalone register https://codepush-<project_suffix>.azurewebsites.net`. 
It now lands to 
https://codepush-<project_suffix>.azurewebsites.net/auth/register?hostname=<HOST_NAME>. 
But now shows a blank page with 
`Cannot GET /auth/register`
The console log is `Failed to load resource: the server responded with a status of 404 (Not Found)`.
What am I missing here to complete the authentication?

3) While trying to get this to work in Azure Web portal I navigated to 
`codepush-<project_suffix>` Web App.
Inside `Settings -> Authentication` tab I selected `Github Identity` provider. 
Do you know if this step is required? </strike>

**EDIT**
After deployment, we must add the `api` folder code to the deployed appservice. There are two ways
1) VS Code add Azure App Service extension. Login to your account. Under your resource select `App Services` -> Right click on your resource and select `Deploy to Web App` followed by selecting the location of `api` folder.
2) The second way is by going to the portal online, cloning your git account and uploading the `api` folder there. The credentials can be found here.
![Image](https://github.com/user-attachments/assets/388ea711-ba2b-42df-9d15-1c5fe5009b74)

Hope that helps

**Comment by veaniswich** [comment]
@jerinjohnk You need to copy the code in the api directory to the newly created repository, and then deploy it to Azure to run it. For specific steps, see how to deploy a webapp service

**Comment by jerinjohnk** [comment]
Thanks, @veaniswich , for pointing me in the right direction; I was missing this step. I have updated my question with the solution that I found.
