### ISSUE TITLE
iOS CodePushServerURL plist doesn't like //

### ISSUE THREAD

**Issue by kmcrawford** [microsoft/code-push-server#41]
When setting up the info.plist to include the `CodePushServerURL`

Example:
```
<key>CodePushServerURL</key>
<string>https://mycode-push.server.com</string>
```

You get this error: (masked)

```
error: unable to read property list from file: /Users/****/Library/Developer/Xcode/DerivedData/**_mobile-**/Build/Intermediates.noindex/tw_mobile.build/Debug-iphonesimulator/**_mobile.build/Preprocessed-Info.plist: The operation couldn’t be completed. (XCBUtil.PropertyListConversionError error 2.) (in target '**_mobile' from project '**_mobile')
```

If I look at the `Preprocessed-Info.plist ` I see the following:
```
<key>CodePushServerURL</key>
 <string>https:
 <key>UIViewControllerBasedStatusBarAppearance</key>
 <false/>
```

The end of the string is missing, I'm not sure it likes the `//`.  I could wrap this in double quotes to get it to build but I'm not sure if that will cause additional issues.

**Comment by kmcrawford** [comment]
I was able to get around this issue by setting the plist to:
```
<key>CodePushServerURL</key>
<string>$(CODE_PUSH_SERVER_URL)</string>
```

Then:
	1.	Open Xcode and go to your project’s Build Settings.
	2.	Add a new User-Defined Setting. Name it  `CODE_PUSH_SERVER_URL` and set its value to <server-url>

**Comment by ahsanparacha02** [comment]
@kmcrawford what are the steps for setting up with live servers

**Comment by kmcrawford** [comment]
Perhaps this issue should be with https://github.com/microsoft/react-native-code-push repo
