### ISSUE TITLE
Code push Live Server Configuration

### ISSUE THREAD

**Issue by ahsanparacha02** [microsoft/code-push-server#45]
I’ve configured code push with localhost, and it was working. Now, I’d like to configure it with a live server. I have a few questions:

- Is it possible to configure code push with a live server like https://lky.com, or does it require configuration exclusively with an Azure App Service?
- After setting up the server, should we only move the API folder to the server?
- Once the server is set up, how should we use Azurite with the live server?

Thanks

**Comment by jerinjohnk** [comment]
1) People have forked this repo and modified it to be used with different cloud servers, such as AWS. You can also try them.
2) In the setup, there is a `codepush-infrastructure.bicep` file that sets up all your required services. 
Once it is done, you need to copy the contents of the `api' folder to your app services. 
Please feel free to refer to #40 for detailed steps.
3) Azurite is for testing locally. 
Once the server is set up, you will upload your packages to the server, and they will be downloaded to your app.

**Comment by ahsanparacha02** [comment]
> 1. People have forked this repo and modified it to be used with different cloud servers, such as AWS. You can also try them.
> 2. In the setup, there is a `codepush-infrastructure.bicep` file that sets up all your required services.
>    Once it is done, you need to copy the contents of the `api' folder to your app services.
>    Please feel free to refer to [Switching to Azure Storage from local not working #40](https://github.com/microsoft/code-push-server/issues/40) for detailed steps.
> 3. Azurite is for testing locally.
>    Once the server is set up, you will upload your packages to the server, and they will be downloaded to your app.

@jerinjohnk which specific changes required to change for cloud server, and where i can change them

**Comment by jerinjohnk** [comment]
I didn't get which specific changes you require.
Specific changes for
Point 1 - Please refer to the different forks of this repo. For example [AWS S3 Fork](https://github.com/nmengual/code-push-server)
Point 2 - details are provided in the edited question section of #40 
Point 3 - its self explanatory.

**Comment by ahsanparacha02** [comment]
> 1. People have forked this repo and modified it to be used with different cloud servers, such as AWS. You can also try them.
> 2. In the setup, there is a `codepush-infrastructure.bicep` file that sets up all your required services.
>    Once it is done, you need to copy the contents of the `api' folder to your app services.
>    Please feel free to refer to [Switching to Azure Storage from local not working #40](https://github.com/microsoft/code-push-server/issues/40) for detailed steps.
> 3. Azurite is for testing locally.
>    Once the server is set up, you will upload your packages to the server, and they will be downloaded to your app.

@jerinjohnk which specific changes required to change

**Comment by ahsanparacha02** [comment]
> I didn't get which specific changes you require. Specific changes for Point 1 - Please refer to the different forks of this repo. For example [AWS S3 Fork](https://github.com/nmengual/code-push-server) Point 2 - details are provided in the edited question section of [#40](https://github.com/microsoft/code-push-server/issues/40) Point 3 - its self explanatory.

i have setup server  on azure and it running but when i try to logout and login with new server then i am getting below mention error.

![Image](https://github.com/user-attachments/assets/4c30a52f-6851-4467-b178-37670dbf2c32)

How to fixed this issue ?

**Comment by jerinjohnk** [comment]
It might be because you were logged in when you ran this locally and forgot to **logout** before running the register/login using the Azure server.
1) From your locally run server, log out before registering the Azure one.
2) I did try the `link` command, but it didn't work.
3) Other than these, I revoked the registered permission from GitHub and updated the redirection URLs there.
Optional: I'm unsure but also ran `rm -rf ~/.appcenter-cli/profile.json`. **I'm just warning you**: This will delete your current App Center profiles, and you might need to log in again.

**Comment by ahsanparacha02** [comment]
> It might be because you were logged in when you ran this locally and forgot to **logout** before running the register/login using the Azure server.
> 
> 1. From your locally run server, log out before registering the Azure one.
> 2. I did try the `link` command, but it didn't work.
> 3. Other than these, I revoked the registered permission from GitHub and updated the redirection URLs there.
>    Optional: I'm unsure but also ran `rm -rf ~/.appcenter-cli/profile.json`. **I'm just warning you**: This will delete your current App Center profiles, and you might need to log in again.

Thanks @jerinjohnk, its working fine now.
