### ISSUE TITLE
Allow Redis TLS to be disabled

### ISSUE THREAD

**Issue by kmcrawford** [microsoft/code-push-server#47]
If using a custom installation of Redis the adding `REDIS_TLS_DISABLED` allows for optional Redis configuration.

```
 const redisConfig = {
        host: process.env.REDIS_HOST,
        port: process.env.REDIS_PORT,
      };
      if (process.env.REDIS_KEY) {
        redisConfig["auth_pass"] = process.env.REDIS_KEY;
      }
      if (!process.env.REDIS_TLS_DISABLED) {
        redisConfig["tls"] = {
          rejectUnauthorized: true,
        };
      }
```

**Comment by kmcrawford** [comment]
Additionally this also allows for optional `REDIS_KEY` 
The current code has it as required, when the documentation has it as optional.

https://github.com/microsoft/code-push-server/blob/main/api/script/redis-manager.ts#L105

**Comment by lucen-ms** [comment]
We have updated the documentation:
* Redis is required for Metrics to work.
* TLS is required for Redis.
