### ISSUE TITLE
I was relying on -use-hermes but there is no support for hermes in this cli.

### ISSUE THREAD

**Issue by khalisafkari** [microsoft/code-push-server#5]
Before I relied on -use-hermes on appcenter-cli but on this cli there is no hermes support, my application without using -use-hermes update always fails to be applied.

**Comment by lucen-ms** [comment]
I'm sorry the current version does not support Hermes but we will add it soon to have a feature parity with the current `appcenter-cli` version.

**Comment by khalisafkari** [comment]
> I'm sorry the current version does not support Hermes but we will add it soon to have a feature parity with the current `appcenter-cli` version.

This is a very good news

**Comment by bogas04** [comment]
@lucen-ms Would it be possible to share a potential timeline for the same? Is "soon" weeks or months?

**Comment by lucen-ms** [comment]
It's 1-2 weeks.

**Comment by lucen-ms** [comment]
Hermes support has been implemented.
